# Generated by Django 2.2.6 on 2020-11-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.BooleanField(default=False),
        ),
    ]
